Various updates
madScripting/BigWigs-TurtleWoW pull request #4
Opened 2024-04-20 20:19 UTC by pepopo978

add bars for important buffs like lip/invis/bop
add reset position to messages
read defaults in modules
fix razuvious first shout timer

2024-04-20 20:19 UTC, pepopo978 commented
some updates you might be interested in

2024-04-20 20:22 UTC, pepopo978 commented on Core.lua
> +			if module.defaultDB and module.defaultDB[v] ~= nil then
realized you didn't have this (maybe from balake?), can default certain alerts to off

2024-05-05 20:42 UTC, madScripting requested changes
I've manually merged the 4 other files, just not Razuvious.

2024-05-05 20:42 UTC, madScripting commented on Raids/Naxxramas/Razuvious.lua
If I am not mistaken, if the timer IS accurate, and the person is NOT targetting Razuvious on pull, and then targets Razuvious 5 seconds later, it will make the timer NOT accurate, right?

Considering the only thing that makes the timer not accurate is if someone is using an old ass BigWigs version... That doesn't seem to be a worthy fix.

Looping through the raid, finding someone that has Razuvious targetted, verifying if Razuvious has a target, might be better?

2024-05-06 21:20 UTC, pepopo978 commented on Raids/Naxxramas/Razuvious.lua
Hmm have you done razuvious recently?  I was using your latest version before and timer was always wrong because he doesn't enter combat when players do.  He enters combat a few seconds later when he gets close enough to MC'ed target and aggroes onto it.

2024-05-06 21:23 UTC, pepopo978 commented on Raids/Naxxramas/Razuvious.lua
> verifying if Razuvious has a target
can you do this without targeting him?  with superwow you can.  But yea just need some way to detect when he actually targets the MC'ed soldier

2024-05-06 21:31 UTC, pepopo978 commented on Raids/Naxxramas/Razuvious.lua
ah yea can do `UnitName("targettargettarget")` hehe, I'll update

2024-05-06 22:00 UTC, pepopo978 commented on Raids/Naxxramas/Razuvious.lua
tested on vmangos seems to be working, turtle razuvious logic is custom so not a perfect test

2024-05-06 22:54 UTC, madScripting commented on Raids/Naxxramas/Razuvious.lua
> Hmm have you done razuvious recently? I was using your latest version before and first timer was always wrong because he doesn't enter combat when players do. He enters combat a few seconds later when he gets close enough to MC'ed target and aggroes onto it.

Yes, that is due to the old BigWigs having the adds as combat detection. Once the old BigWigs detects combat has started (falsely), it syncs everyone to engage combat.
Only 1 bad BigWigs in the raid will desync everyone else's.
With all good BigWigs, the timer is accurate.

2024-05-07 01:52 UTC, pmaccamp commented on Raids/Naxxramas/Razuvious.lua
ah interesting well hard to get all 40 people to update but makes sense you don't wanna merge in a workaround.

Don't bigwig events have the module version in them?  Could you ignore old combat started events?

2024-05-07 01:52 UTC, pepopo978 commented on Raids/Naxxramas/Razuvious.lua
ah interesting well hard to get all 40 people to update but makes sense you don't wanna merge in a workaround.

Don't bigwig events have the module version in them?  Could you ignore old combat started events?

2024-07-07 15:43 UTC, closed without merging